### ISSUE TITLE
error: Error importing plugin "returns.contrib.mypy.returns_plugin": No module named 'returns'  [misc]

### ISSUE THREAD

**Issue by wizard-28** [dry-python/returns#1577]
# Bug report

## What's wrong

Mypy is unable to use the plugin. It errors out with the following message:

```
error: Error importing plugin "returns.contrib.mypy.returns_plugin": No module named 'returns'  [misc]
```

Here's my `pyproject.toml`:

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Sourajyoti Basak <wiz28@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
returns = "^0.19.0"
mypy = "^0.950"

[tool.mypy]
plugins = ["returns.contrib.mypy.returns_plugin"]
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

## How is that should be

mypy successfully works.

## System information

- `python` version: `3.10.6`
- `returns` version: `0.19.0`
- `mypy` version: `0.950`
