### ISSUE TITLE
Unit method like `IOResultE.from_value` must return `IOResult[_V, Exception]` type

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#407]
Currently, they do return incorrect types:

```python
reveal_type(IOResultE.from_value(int))
# => IOResult[int, Any]
```

To achieve what we want we might tweak the way we create an alias in some way:
1. We can use inheritance instead
2. We can use some magic
3. mypy plugin?

**Comment by sobolevn** [comment]
The same applies for all aliases with `E` suffix: `ResultE`, `IOResultE`, `FutureResultE`, `ReaderResultE`, etc

**Comment by thepabloaguilar** [comment]
Inheritance does not work:
```python
class IOResultE(IOResult[_ValueType, Exception]):
    pass

reveal_type(IOResultE.from_value(42))  # N: Revealed type is 'returns.io.IOResult[builtins.int*, builtins.Exception*]'
```
Output:
```text
main:6: note: Revealed type is 'returns.io.IOResult[builtins.int*, Any]'
```

**Comment by thepabloaguilar** [comment]
I got it, the actual signature is:
```python
class IOResult:
    def from_value(cls, inner_value: _NewValueType) -> 'IOResult[_NewValueType, Any]':
        ...
```

I've just adjusted the return type to:
```python
class IOResult:
    def from_value(cls, inner_value: _NewValueType) -> 'IOResult[_NewValueType, _ErrorType]':
        ...
```
Test case:
```yml
- case: test_io_result_e_from
  disable_cache: true
  main: |
    from returns.io import IOResultE

    reveal_type(IOResultE.from_value(10))  # N: Revealed type is 'returns.io.IOResult[builtins.int*, builtins.Exception]'
```

**Comment by sobolevn** [comment]
@thepabloaguilar can you please test that these tests still work: https://github.com/dry-python/returns/blob/master/typesafety/test_io/test_ioresult_container/test_ioresult_typecast.yml ?

**Comment by thepabloaguilar** [comment]
Just one test was broken:
```yml
- case: ioresult_from_value
  disable_cache: true
  main: |
    from returns.io import IOResult

    reveal_type(IOResult.from_value(1))  # N: Revealed type is 'returns.io.IOResult[builtins.int*, Any]'
```
Output:
```text
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Invalid output: 
E   Expected:
E     main:3: note: Revealed type is 'returns.io.IOResult[builtins.int*, Any]' (diff)
E   Actual:
E     main:3: note: Revealed type is 'returns.io.IOResult[builtins.int*, <nothing>]' (diff)
E   
E   Alignment of first line difference:
E     E: ...io.IOResult[builtins.int*, Any]'
E     A: ...io.IOResult[builtins.int*, <nothing>]'
```
